pipeline {
    agent any

    environment {
        TF_IN_AUTOMATION = "true"
    }

    stages {

        stage('Terraform Init') {
            steps {
                dir('DevOps/azure-landing-zone') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('DevOps/azure-landing-zone') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('DevOps/azure-landing-zone') {
                    sh 'terraform plan'
                }
            }
        }
    }
}