pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'ROLLBACK',
            defaultValue: false,
            description: 'Tick only if you want to rollback previous Kubernetes deployment'
        )
    }

    stages {

        stage('Rollback') {
            when {
                expression { params.ROLLBACK == true }
            }
            steps {
                dir('DevOps/Docker_Projects/simple-webapp') {
                    sh '''
                    echo "Manual rollback started..."

                    kubectl rollout undo deployment enterprise-webapp-deployment
                    kubectl rollout status deployment enterprise-webapp-deployment

                    echo "Rollback completed."
                    '''
                }
            }
        }

        stage('Deploy') {
            when {
                expression { params.ROLLBACK == false }
            }
            steps {
                dir('DevOps/Docker_Projects/simple-webapp') {
                    sh '''
                    echo "Auto deployment started..."

                    IMAGE_TAG=build-${BUILD_NUMBER}
                    IMAGE_NAME=enterprise-webapp-jenkins:${IMAGE_TAG}

                    echo "Building image: $IMAGE_NAME"

                    docker build -t $IMAGE_NAME .
                    kind load docker-image $IMAGE_NAME --name cicd-lab

                    kubectl apply -f k8s/service.yaml
                    kubectl apply -f k8s/deployment.yaml

                    kubectl set image deployment/enterprise-webapp-deployment enterprise-webapp=$IMAGE_NAME

                    kubectl rollout status deployment enterprise-webapp-deployment

                    echo "Deployment completed with image: $IMAGE_NAME"
                    '''
                }
            }
        }
    }
}