pipeline {
    agent any

    environment {
        IMAGE_NAME = "enterprise-webapp-jenkins:v1"
        CONTAINER_NAME = "enterprise-webapp"
    }

    stages {

        stage('Show Files') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('DevOps/Docker_Projects/simple-webapp') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh 'docker rm -f $CONTAINER_NAME || true'
            }
        }

        stage('Run New Container') {
            steps {
                sh 'docker run -d --name $CONTAINER_NAME -p 8090:80 $IMAGE_NAME'
            }
        }

        stage('Verify Running Container') {
            steps {
                sh 'docker ps'
            }
        }
    }

    post {
        success {
            echo 'Docker deployment completed successfully'
        }

        failure {
            echo 'Docker deployment failed'
        }
    }
}