pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                echo 'Code pulled from GitHub'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t enterprise-webapp-jenkins:v1 .'
            }
        }

        stage('Remove Old Container') {
            steps {
                sh 'docker rm -f enterprise-webapp || true'
            }
        }

        stage('Run New Container') {
            steps {
                sh 'docker run -d --name enterprise-webapp -p 8090:80 enterprise-webapp-jenkins:v1'
            }
        }
    }
}